source 'https://rubygems.org'

ruby '2.1.2'

gem 'aasm'
gem 'active_model_serializers'
gem 'activeadmin', github: 'gregbell/active_admin'
gem 'angular-ui-bootstrap-rails'
gem 'angularjs-rails'
gem 'apipie-rails'
gem 'bootstrap-sass'
gem 'cancan'
gem 'coffee-rails'
gem 'coffeelint'
gem 'devise'
gem 'dragonfly'
gem 'dragonfly-s3_data_store'
gem 'faraday'
gem 'font-awesome-rails'
gem 'gmaps4rails'
gem 'geokit-rails'
gem 'jquery-rails'
gem 'koala'
gem 'newrelic_rpm'
gem 'pg'
gem 'rails', '4.1.0'
gem 'rails_12factor'
gem 'rubocop'
gem 'sass-rails', '4.0.2'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'underscore-rails'

group :production do
  gem 'bugsnag'
  gem 'rack-cache', require: 'rack/cache'
end

group :development, :test do
  gem 'byebug'
  gem 'debugger-ruby_core_source'
  gem 'factory_girl_rails'
  gem 'quiet_assets'
  gem 'rspec-rails'
end
